// Code generated by protoc-gen-go-bnet. DO NOT EDIT.

package game_utilities_service

import (
	"context"
	"strings"
)

// GameUtilitiesServiceHash is the hash of the service name
const GameUtilitiesServiceHash uint32 = 1368537640 // bgs.protocol.game_utilities.v1.GameUtilitiesService
// GameUtilitiesServiceOriginalFullyQualifiedDescriptorName is the original fully qualified descriptor name
const GameUtilitiesServiceOriginalFullyQualifiedDescriptorName string = "bnet.protocol.game_utilities.GameUtilities"

// GameUtilitiesServiceOriginalFullyQualifiedDescriptorNameHash is the hash of the original fully qualified descriptor name
const GameUtilitiesServiceOriginalFullyQualifiedDescriptorNameHash uint32 = 1069623117 // bnet.protocol.game_utilities.GameUtilities

// GameUtilitiesService is the client API for bgs.protocol.game_utilities.v1.GameUtilitiesService
type GameUtilitiesService interface {
	// ProcessClientRequest has a method id of 1 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessClientRequest
	ProcessClientRequest(context.Context, *ClientRequest, interface{}) error
	// PresenceChannelCreated has a method id of 2 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.PresenceChannelCreated
	PresenceChannelCreated(context.Context, *PresenceChannelCreatedRequest, interface{}) error
	// GetPlayerVariables has a method id of 3 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.GetPlayerVariables
	GetPlayerVariables(context.Context, *GetPlayerVariablesRequest, interface{}) error
	// ProcessServerRequest has a method id of 6 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessServerRequest
	ProcessServerRequest(context.Context, *ServerRequest, interface{}) error
	// OnGameAccountOnline has a method id of 7 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOnline
	OnGameAccountOnline(context.Context, *GameAccountOnlineNotification, interface{}) error
	// OnGameAccountOffline has a method id of 8 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOffline
	OnGameAccountOffline(context.Context, *GameAccountOfflineNotification, interface{}) error
	// GetAchievementsFile has a method id of 9 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAchievementsFile
	GetAchievementsFile(context.Context, *GetAchievementsFileRequest, interface{}) error
	// GetAllValuesForAttribute has a method id of 10 and a method name of bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAllValuesForAttribute
	GetAllValuesForAttribute(context.Context, *GetAllValuesForAttributeRequest, interface{}) error
}

// GameUtilitiesServiceMethods is a map of method ids to method names
var GameUtilitiesServiceMethods = map[uint32]string{
	1:  "bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessClientRequest",
	2:  "bgs.protocol.game_utilities.v1.GameUtilitiesService.PresenceChannelCreated",
	3:  "bgs.protocol.game_utilities.v1.GameUtilitiesService.GetPlayerVariables",
	6:  "bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessServerRequest",
	7:  "bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOnline",
	8:  "bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOffline",
	9:  "bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAchievementsFile",
	10: "bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAllValuesForAttribute",
}

// GameUtilitiesServiceMethod is the method id for bgs.protocol.game_utilities.v1.GameUtilitiesService
type GameUtilitiesServiceMethod uint32

// Enum value maps for GameUtilitiesServiceMethod.
const (
	// GameUtilitiesServiceMethod_ProcessClientRequest GameUtilitiesServiceMethod = 1 // bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessClientRequest
	GameUtilitiesServiceMethod_ProcessClientRequest GameUtilitiesServiceMethod = 1 // bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessClientRequest
	// GameUtilitiesServiceMethod_PresenceChannelCreated GameUtilitiesServiceMethod = 2 // bgs.protocol.game_utilities.v1.GameUtilitiesService.PresenceChannelCreated
	GameUtilitiesServiceMethod_PresenceChannelCreated GameUtilitiesServiceMethod = 2 // bgs.protocol.game_utilities.v1.GameUtilitiesService.PresenceChannelCreated
	// GameUtilitiesServiceMethod_GetPlayerVariables GameUtilitiesServiceMethod = 3 // bgs.protocol.game_utilities.v1.GameUtilitiesService.GetPlayerVariables
	GameUtilitiesServiceMethod_GetPlayerVariables GameUtilitiesServiceMethod = 3 // bgs.protocol.game_utilities.v1.GameUtilitiesService.GetPlayerVariables
	// GameUtilitiesServiceMethod_ProcessServerRequest GameUtilitiesServiceMethod = 6 // bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessServerRequest
	GameUtilitiesServiceMethod_ProcessServerRequest GameUtilitiesServiceMethod = 6 // bgs.protocol.game_utilities.v1.GameUtilitiesService.ProcessServerRequest
	// GameUtilitiesServiceMethod_OnGameAccountOnline GameUtilitiesServiceMethod = 7 // bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOnline
	GameUtilitiesServiceMethod_OnGameAccountOnline GameUtilitiesServiceMethod = 7 // bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOnline
	// GameUtilitiesServiceMethod_OnGameAccountOffline GameUtilitiesServiceMethod = 8 // bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOffline
	GameUtilitiesServiceMethod_OnGameAccountOffline GameUtilitiesServiceMethod = 8 // bgs.protocol.game_utilities.v1.GameUtilitiesService.OnGameAccountOffline
	// GameUtilitiesServiceMethod_GetAchievementsFile GameUtilitiesServiceMethod = 9 // bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAchievementsFile
	GameUtilitiesServiceMethod_GetAchievementsFile GameUtilitiesServiceMethod = 9 // bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAchievementsFile
	// GameUtilitiesServiceMethod_GetAllValuesForAttribute GameUtilitiesServiceMethod = 10 // bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAllValuesForAttribute
	GameUtilitiesServiceMethod_GetAllValuesForAttribute GameUtilitiesServiceMethod = 10 // bgs.protocol.game_utilities.v1.GameUtilitiesService.GetAllValuesForAttribute
)

// ToUint32 converts a GameUtilitiesServiceMethod enum to a uint32
func (m GameUtilitiesServiceMethod) ToUint32() uint32 {
	return uint32(m)
}

// GetMethodFullName returns the method full name for the given method id
func (m GameUtilitiesServiceMethod) GetMethodFullName() string {
	return GameUtilitiesServiceMethods[uint32(m)]
}

// GetMethodName returns the method name for the given method id
func (m GameUtilitiesServiceMethod) GetMethodName() string {
	if _, ok := GameUtilitiesServiceMethods[uint32(m)]; !ok {
		return "No Method Exist"
	}
	return GameUtilitiesServiceMethods[uint32(m)][strings.LastIndex(GameUtilitiesServiceMethods[uint32(m)], ".")+1:]
}
