// Code generated by protoc-gen-go-bnet. DO NOT EDIT.

package authentication_service

import (
	entity_types "bnet-mock/network/client/entity_types"
	rpc_types "bnet-mock/network/client/rpc_types"
)

import (
	"context"
	"strings"
)

// AuthenticationListenerHash is the hash of the service name
const AuthenticationListenerHash uint32 = 1302880808 // bgs.protocol.authentication.v1.AuthenticationListener
// AuthenticationListenerOriginalFullyQualifiedDescriptorName is the original fully qualified descriptor name
const AuthenticationListenerOriginalFullyQualifiedDescriptorName string = "bnet.protocol.authentication.AuthenticationClient"

// AuthenticationListenerOriginalFullyQualifiedDescriptorNameHash is the hash of the original fully qualified descriptor name
const AuthenticationListenerOriginalFullyQualifiedDescriptorNameHash uint32 = 1898188341 // bnet.protocol.authentication.AuthenticationClient

// AuthenticationListener is the client API for bgs.protocol.authentication.v1.AuthenticationListener
type AuthenticationListener interface {
	// Deprecated: OnModuleLoad has a method id of 1 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnModuleLoad
	OnModuleLoad(context.Context, *ModuleLoadRequest, interface{}) error
	// Deprecated: OnModuleMessage has a method id of 2 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnModuleMessage
	OnModuleMessage(context.Context, *ModuleMessageRequest, interface{}) error
	// OnServerStateChange has a method id of 4 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnServerStateChange
	OnServerStateChange(context.Context, *ServerStateChangeRequest, interface{}) error
	// OnLogonComplete has a method id of 5 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnLogonComplete
	OnLogonComplete(context.Context, *LogonResult, interface{}) error
	// OnMemModuleLoad has a method id of 6 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnMemModuleLoad
	OnMemModuleLoad(context.Context, *MemModuleLoadRequest, interface{}) error
	// OnLogonUpdate has a method id of 10 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnLogonUpdate
	OnLogonUpdate(context.Context, *LogonUpdateRequest, interface{}) error
	// OnVersionInfoUpdated has a method id of 11 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnVersionInfoUpdated
	OnVersionInfoUpdated(context.Context, *VersionInfoNotification, interface{}) error
	// OnLogonQueueUpdate has a method id of 12 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueUpdate
	OnLogonQueueUpdate(context.Context, *LogonQueueUpdateRequest, interface{}) error
	// OnLogonQueueEnd has a method id of 13 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueEnd
	OnLogonQueueEnd(context.Context, *rpc_types.NoData, interface{}) error
	// Deprecated: OnGameAccountSelected has a method id of 14 and a method name of bgs.protocol.authentication.v1.AuthenticationListener.OnGameAccountSelected
	OnGameAccountSelected(context.Context, *GameAccountSelectedRequest, interface{}) error
}

// AuthenticationListenerMethods is a map of method ids to method names
var AuthenticationListenerMethods = map[uint32]string{
	1:  "bgs.protocol.authentication.v1.AuthenticationListener.OnModuleLoad",
	2:  "bgs.protocol.authentication.v1.AuthenticationListener.OnModuleMessage",
	4:  "bgs.protocol.authentication.v1.AuthenticationListener.OnServerStateChange",
	5:  "bgs.protocol.authentication.v1.AuthenticationListener.OnLogonComplete",
	6:  "bgs.protocol.authentication.v1.AuthenticationListener.OnMemModuleLoad",
	10: "bgs.protocol.authentication.v1.AuthenticationListener.OnLogonUpdate",
	11: "bgs.protocol.authentication.v1.AuthenticationListener.OnVersionInfoUpdated",
	12: "bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueUpdate",
	13: "bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueEnd",
	14: "bgs.protocol.authentication.v1.AuthenticationListener.OnGameAccountSelected",
}

// AuthenticationListenerMethod is the method id for bgs.protocol.authentication.v1.AuthenticationListener
type AuthenticationListenerMethod uint32

// Enum value maps for AuthenticationListenerMethod.
const (
	// AuthenticationListenerMethod_OnModuleLoad AuthenticationListenerMethod = 1 // bgs.protocol.authentication.v1.AuthenticationListener.OnModuleLoad
	AuthenticationListenerMethod_OnModuleLoad AuthenticationListenerMethod = 1 // bgs.protocol.authentication.v1.AuthenticationListener.OnModuleLoad
	// AuthenticationListenerMethod_OnModuleMessage AuthenticationListenerMethod = 2 // bgs.protocol.authentication.v1.AuthenticationListener.OnModuleMessage
	AuthenticationListenerMethod_OnModuleMessage AuthenticationListenerMethod = 2 // bgs.protocol.authentication.v1.AuthenticationListener.OnModuleMessage
	// AuthenticationListenerMethod_OnServerStateChange AuthenticationListenerMethod = 4 // bgs.protocol.authentication.v1.AuthenticationListener.OnServerStateChange
	AuthenticationListenerMethod_OnServerStateChange AuthenticationListenerMethod = 4 // bgs.protocol.authentication.v1.AuthenticationListener.OnServerStateChange
	// AuthenticationListenerMethod_OnLogonComplete AuthenticationListenerMethod = 5 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonComplete
	AuthenticationListenerMethod_OnLogonComplete AuthenticationListenerMethod = 5 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonComplete
	// AuthenticationListenerMethod_OnMemModuleLoad AuthenticationListenerMethod = 6 // bgs.protocol.authentication.v1.AuthenticationListener.OnMemModuleLoad
	AuthenticationListenerMethod_OnMemModuleLoad AuthenticationListenerMethod = 6 // bgs.protocol.authentication.v1.AuthenticationListener.OnMemModuleLoad
	// AuthenticationListenerMethod_OnLogonUpdate AuthenticationListenerMethod = 10 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonUpdate
	AuthenticationListenerMethod_OnLogonUpdate AuthenticationListenerMethod = 10 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonUpdate
	// AuthenticationListenerMethod_OnVersionInfoUpdated AuthenticationListenerMethod = 11 // bgs.protocol.authentication.v1.AuthenticationListener.OnVersionInfoUpdated
	AuthenticationListenerMethod_OnVersionInfoUpdated AuthenticationListenerMethod = 11 // bgs.protocol.authentication.v1.AuthenticationListener.OnVersionInfoUpdated
	// AuthenticationListenerMethod_OnLogonQueueUpdate AuthenticationListenerMethod = 12 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueUpdate
	AuthenticationListenerMethod_OnLogonQueueUpdate AuthenticationListenerMethod = 12 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueUpdate
	// AuthenticationListenerMethod_OnLogonQueueEnd AuthenticationListenerMethod = 13 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueEnd
	AuthenticationListenerMethod_OnLogonQueueEnd AuthenticationListenerMethod = 13 // bgs.protocol.authentication.v1.AuthenticationListener.OnLogonQueueEnd
	// AuthenticationListenerMethod_OnGameAccountSelected AuthenticationListenerMethod = 14 // bgs.protocol.authentication.v1.AuthenticationListener.OnGameAccountSelected
	AuthenticationListenerMethod_OnGameAccountSelected AuthenticationListenerMethod = 14 // bgs.protocol.authentication.v1.AuthenticationListener.OnGameAccountSelected
)

// ToUint32 converts a AuthenticationListenerMethod enum to a uint32
func (m AuthenticationListenerMethod) ToUint32() uint32 {
	return uint32(m)
}

// GetMethodFullName returns the method full name for the given method id
func (m AuthenticationListenerMethod) GetMethodFullName() string {
	return AuthenticationListenerMethods[uint32(m)]
}

// GetMethodName returns the method name for the given method id
func (m AuthenticationListenerMethod) GetMethodName() string {
	if _, ok := AuthenticationListenerMethods[uint32(m)]; !ok {
		return "No Method Exist"
	}
	return AuthenticationListenerMethods[uint32(m)][strings.LastIndex(AuthenticationListenerMethods[uint32(m)], ".")+1:]
}

// AuthenticationServiceHash is the hash of the service name
const AuthenticationServiceHash uint32 = 4284115651 // bgs.protocol.authentication.v1.AuthenticationService
// AuthenticationServiceOriginalFullyQualifiedDescriptorName is the original fully qualified descriptor name
const AuthenticationServiceOriginalFullyQualifiedDescriptorName string = "bnet.protocol.authentication.AuthenticationServer"

// AuthenticationServiceOriginalFullyQualifiedDescriptorNameHash is the hash of the original fully qualified descriptor name
const AuthenticationServiceOriginalFullyQualifiedDescriptorNameHash uint32 = 233634817 // bnet.protocol.authentication.AuthenticationServer

// AuthenticationService is the client API for bgs.protocol.authentication.v1.AuthenticationService
type AuthenticationService interface {
	// Logon has a method id of 1 and a method name of bgs.protocol.authentication.v1.AuthenticationService.Logon
	Logon(context.Context, *LogonRequest, interface{}) error
	// Deprecated: ModuleNotify has a method id of 2 and a method name of bgs.protocol.authentication.v1.AuthenticationService.ModuleNotify
	ModuleNotify(context.Context, *ModuleNotification, interface{}) error
	// Deprecated: ModuleMessage has a method id of 3 and a method name of bgs.protocol.authentication.v1.AuthenticationService.ModuleMessage
	ModuleMessage(context.Context, *ModuleMessageRequest, interface{}) error
	// Deprecated: SelectGameAccount_DEPRECATED has a method id of 4 and a method name of bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount_DEPRECATED
	SelectGameAccount_DEPRECATED(context.Context, *entity_types.EntityId, interface{}) error
	// GenerateSSOToken has a method id of 5 and a method name of bgs.protocol.authentication.v1.AuthenticationService.GenerateSSOToken
	GenerateSSOToken(context.Context, *GenerateSSOTokenRequest, interface{}) error
	// Deprecated: SelectGameAccount has a method id of 6 and a method name of bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount
	SelectGameAccount(context.Context, *SelectGameAccountRequest, interface{}) error
	// VerifyWebCredentials has a method id of 7 and a method name of bgs.protocol.authentication.v1.AuthenticationService.VerifyWebCredentials
	VerifyWebCredentials(context.Context, *VerifyWebCredentialsRequest, interface{}) error
	// GenerateWebCredentials has a method id of 8 and a method name of bgs.protocol.authentication.v1.AuthenticationService.GenerateWebCredentials
	GenerateWebCredentials(context.Context, *GenerateWebCredentialsRequest, interface{}) error
}

// AuthenticationServiceMethods is a map of method ids to method names
var AuthenticationServiceMethods = map[uint32]string{
	1: "bgs.protocol.authentication.v1.AuthenticationService.Logon",
	2: "bgs.protocol.authentication.v1.AuthenticationService.ModuleNotify",
	3: "bgs.protocol.authentication.v1.AuthenticationService.ModuleMessage",
	4: "bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount_DEPRECATED",
	5: "bgs.protocol.authentication.v1.AuthenticationService.GenerateSSOToken",
	6: "bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount",
	7: "bgs.protocol.authentication.v1.AuthenticationService.VerifyWebCredentials",
	8: "bgs.protocol.authentication.v1.AuthenticationService.GenerateWebCredentials",
}

// AuthenticationServiceMethod is the method id for bgs.protocol.authentication.v1.AuthenticationService
type AuthenticationServiceMethod uint32

// Enum value maps for AuthenticationServiceMethod.
const (
	// AuthenticationServiceMethod_Logon AuthenticationServiceMethod = 1 // bgs.protocol.authentication.v1.AuthenticationService.Logon
	AuthenticationServiceMethod_Logon AuthenticationServiceMethod = 1 // bgs.protocol.authentication.v1.AuthenticationService.Logon
	// AuthenticationServiceMethod_ModuleNotify AuthenticationServiceMethod = 2 // bgs.protocol.authentication.v1.AuthenticationService.ModuleNotify
	AuthenticationServiceMethod_ModuleNotify AuthenticationServiceMethod = 2 // bgs.protocol.authentication.v1.AuthenticationService.ModuleNotify
	// AuthenticationServiceMethod_ModuleMessage AuthenticationServiceMethod = 3 // bgs.protocol.authentication.v1.AuthenticationService.ModuleMessage
	AuthenticationServiceMethod_ModuleMessage AuthenticationServiceMethod = 3 // bgs.protocol.authentication.v1.AuthenticationService.ModuleMessage
	// AuthenticationServiceMethod_SelectGameAccount_DEPRECATED AuthenticationServiceMethod = 4 // bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount_DEPRECATED
	AuthenticationServiceMethod_SelectGameAccount_DEPRECATED AuthenticationServiceMethod = 4 // bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount_DEPRECATED
	// AuthenticationServiceMethod_GenerateSSOToken AuthenticationServiceMethod = 5 // bgs.protocol.authentication.v1.AuthenticationService.GenerateSSOToken
	AuthenticationServiceMethod_GenerateSSOToken AuthenticationServiceMethod = 5 // bgs.protocol.authentication.v1.AuthenticationService.GenerateSSOToken
	// AuthenticationServiceMethod_SelectGameAccount AuthenticationServiceMethod = 6 // bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount
	AuthenticationServiceMethod_SelectGameAccount AuthenticationServiceMethod = 6 // bgs.protocol.authentication.v1.AuthenticationService.SelectGameAccount
	// AuthenticationServiceMethod_VerifyWebCredentials AuthenticationServiceMethod = 7 // bgs.protocol.authentication.v1.AuthenticationService.VerifyWebCredentials
	AuthenticationServiceMethod_VerifyWebCredentials AuthenticationServiceMethod = 7 // bgs.protocol.authentication.v1.AuthenticationService.VerifyWebCredentials
	// AuthenticationServiceMethod_GenerateWebCredentials AuthenticationServiceMethod = 8 // bgs.protocol.authentication.v1.AuthenticationService.GenerateWebCredentials
	AuthenticationServiceMethod_GenerateWebCredentials AuthenticationServiceMethod = 8 // bgs.protocol.authentication.v1.AuthenticationService.GenerateWebCredentials
)

// ToUint32 converts a AuthenticationServiceMethod enum to a uint32
func (m AuthenticationServiceMethod) ToUint32() uint32 {
	return uint32(m)
}

// GetMethodFullName returns the method full name for the given method id
func (m AuthenticationServiceMethod) GetMethodFullName() string {
	return AuthenticationServiceMethods[uint32(m)]
}

// GetMethodName returns the method name for the given method id
func (m AuthenticationServiceMethod) GetMethodName() string {
	if _, ok := AuthenticationServiceMethods[uint32(m)]; !ok {
		return "No Method Exist"
	}
	return AuthenticationServiceMethods[uint32(m)][strings.LastIndex(AuthenticationServiceMethods[uint32(m)], ".")+1:]
}
