// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rest/login.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FormType int32

const (
	FormType_LOGIN_FORM FormType = 1
)

// Enum value maps for FormType.
var (
	FormType_name = map[int32]string{
		1: "LOGIN_FORM",
	}
	FormType_value = map[string]int32{
		"LOGIN_FORM": 1,
	}
)

func (x FormType) Enum() *FormType {
	p := new(FormType)
	*p = x
	return p
}

func (x FormType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FormType) Descriptor() protoreflect.EnumDescriptor {
	return file_rest_login_proto_enumTypes[0].Descriptor()
}

func (FormType) Type() protoreflect.EnumType {
	return &file_rest_login_proto_enumTypes[0]
}

func (x FormType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FormType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FormType(num)
	return nil
}

// Deprecated: Use FormType.Descriptor instead.
func (FormType) EnumDescriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{0}
}

type AuthenticationState int32

const (
	AuthenticationState_LOGIN         AuthenticationState = 1
	AuthenticationState_LEGAL         AuthenticationState = 2
	AuthenticationState_AUTHENTICATOR AuthenticationState = 3
	AuthenticationState_DONE          AuthenticationState = 4
)

// Enum value maps for AuthenticationState.
var (
	AuthenticationState_name = map[int32]string{
		1: "LOGIN",
		2: "LEGAL",
		3: "AUTHENTICATOR",
		4: "DONE",
	}
	AuthenticationState_value = map[string]int32{
		"LOGIN":         1,
		"LEGAL":         2,
		"AUTHENTICATOR": 3,
		"DONE":          4,
	}
)

func (x AuthenticationState) Enum() *AuthenticationState {
	p := new(AuthenticationState)
	*p = x
	return p
}

func (x AuthenticationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationState) Descriptor() protoreflect.EnumDescriptor {
	return file_rest_login_proto_enumTypes[1].Descriptor()
}

func (AuthenticationState) Type() protoreflect.EnumType {
	return &file_rest_login_proto_enumTypes[1]
}

func (x AuthenticationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AuthenticationState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AuthenticationState(num)
	return nil
}

// Deprecated: Use AuthenticationState.Descriptor instead.
func (AuthenticationState) EnumDescriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{1}
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{0}
}

type FormInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputId   *string `protobuf:"bytes,1,req,name=input_id,json=inputId" json:"input_id,omitempty"`
	Type      *string `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Label     *string `protobuf:"bytes,3,req,name=label" json:"label,omitempty"`
	MaxLength *uint32 `protobuf:"varint,4,opt,name=max_length,json=maxLength" json:"max_length,omitempty"`
}

func (x *FormInput) Reset() {
	*x = FormInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormInput) ProtoMessage() {}

func (x *FormInput) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormInput.ProtoReflect.Descriptor instead.
func (*FormInput) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{1}
}

func (x *FormInput) GetInputId() string {
	if x != nil && x.InputId != nil {
		return *x.InputId
	}
	return ""
}

func (x *FormInput) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *FormInput) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *FormInput) GetMaxLength() uint32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

type FormInputs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   *FormType    `protobuf:"varint,1,req,name=type,enum=Battlenet.JSON.Login.FormType" json:"type,omitempty"`
	Inputs []*FormInput `protobuf:"bytes,2,rep,name=inputs" json:"inputs,omitempty"`
}

func (x *FormInputs) Reset() {
	*x = FormInputs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormInputs) ProtoMessage() {}

func (x *FormInputs) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormInputs.ProtoReflect.Descriptor instead.
func (*FormInputs) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{2}
}

func (x *FormInputs) GetType() FormType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return FormType_LOGIN_FORM
}

func (x *FormInputs) GetInputs() []*FormInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type FormInputValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputId *string `protobuf:"bytes,1,req,name=input_id,json=inputId" json:"input_id,omitempty"`
	Value   *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
}

func (x *FormInputValue) Reset() {
	*x = FormInputValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormInputValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormInputValue) ProtoMessage() {}

func (x *FormInputValue) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormInputValue.ProtoReflect.Descriptor instead.
func (*FormInputValue) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{3}
}

func (x *FormInputValue) GetInputId() string {
	if x != nil && x.InputId != nil {
		return *x.InputId
	}
	return ""
}

func (x *FormInputValue) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type LoginForm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformId *string           `protobuf:"bytes,1,req,name=platform_id,json=platformId" json:"platform_id,omitempty"`
	ProgramId  *string           `protobuf:"bytes,2,req,name=program_id,json=programId" json:"program_id,omitempty"`
	Version    *string           `protobuf:"bytes,3,req,name=version" json:"version,omitempty"`
	Inputs     []*FormInputValue `protobuf:"bytes,4,rep,name=inputs" json:"inputs,omitempty"`
}

func (x *LoginForm) Reset() {
	*x = LoginForm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginForm) ProtoMessage() {}

func (x *LoginForm) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginForm.ProtoReflect.Descriptor instead.
func (*LoginForm) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{4}
}

func (x *LoginForm) GetPlatformId() string {
	if x != nil && x.PlatformId != nil {
		return *x.PlatformId
	}
	return ""
}

func (x *LoginForm) GetProgramId() string {
	if x != nil && x.ProgramId != nil {
		return *x.ProgramId
	}
	return ""
}

func (x *LoginForm) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *LoginForm) GetInputs() []*FormInputValue {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type LoginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthenticationState *AuthenticationState `protobuf:"varint,1,req,name=authentication_state,json=authenticationState,enum=Battlenet.JSON.Login.AuthenticationState" json:"authentication_state,omitempty"`
	ErrorCode           *string              `protobuf:"bytes,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorMessage        *string              `protobuf:"bytes,3,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	Url                 *string              `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	LoginTicket         *string              `protobuf:"bytes,5,opt,name=login_ticket,json=loginTicket" json:"login_ticket,omitempty"`
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResult) GetAuthenticationState() AuthenticationState {
	if x != nil && x.AuthenticationState != nil {
		return *x.AuthenticationState
	}
	return AuthenticationState_LOGIN
}

func (x *LoginResult) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *LoginResult) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *LoginResult) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *LoginResult) GetLoginTicket() string {
	if x != nil && x.LoginTicket != nil {
		return *x.LoginTicket
	}
	return ""
}

type LoginRefreshResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginTicketExpiry *uint64 `protobuf:"varint,1,req,name=login_ticket_expiry,json=loginTicketExpiry" json:"login_ticket_expiry,omitempty"`
	IsExpired         *bool   `protobuf:"varint,2,opt,name=is_expired,json=isExpired" json:"is_expired,omitempty"`
}

func (x *LoginRefreshResult) Reset() {
	*x = LoginRefreshResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRefreshResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRefreshResult) ProtoMessage() {}

func (x *LoginRefreshResult) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRefreshResult.ProtoReflect.Descriptor instead.
func (*LoginRefreshResult) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRefreshResult) GetLoginTicketExpiry() uint64 {
	if x != nil && x.LoginTicketExpiry != nil {
		return *x.LoginTicketExpiry
	}
	return 0
}

func (x *LoginRefreshResult) GetIsExpired() bool {
	if x != nil && x.IsExpired != nil {
		return *x.IsExpired
	}
	return false
}

type GameAccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayName       *string `protobuf:"bytes,1,req,name=display_name,json=displayName" json:"display_name,omitempty"`
	Expansion         *uint32 `protobuf:"varint,2,req,name=expansion" json:"expansion,omitempty"`
	IsSuspended       *bool   `protobuf:"varint,3,opt,name=is_suspended,json=isSuspended" json:"is_suspended,omitempty"`
	IsBanned          *bool   `protobuf:"varint,4,opt,name=is_banned,json=isBanned" json:"is_banned,omitempty"`
	SuspensionExpires *uint64 `protobuf:"varint,5,opt,name=suspension_expires,json=suspensionExpires" json:"suspension_expires,omitempty"`
	SuspensionReason  *string `protobuf:"bytes,6,opt,name=suspension_reason,json=suspensionReason" json:"suspension_reason,omitempty"`
}

func (x *GameAccountInfo) Reset() {
	*x = GameAccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAccountInfo) ProtoMessage() {}

func (x *GameAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAccountInfo.ProtoReflect.Descriptor instead.
func (*GameAccountInfo) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{7}
}

func (x *GameAccountInfo) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *GameAccountInfo) GetExpansion() uint32 {
	if x != nil && x.Expansion != nil {
		return *x.Expansion
	}
	return 0
}

func (x *GameAccountInfo) GetIsSuspended() bool {
	if x != nil && x.IsSuspended != nil {
		return *x.IsSuspended
	}
	return false
}

func (x *GameAccountInfo) GetIsBanned() bool {
	if x != nil && x.IsBanned != nil {
		return *x.IsBanned
	}
	return false
}

func (x *GameAccountInfo) GetSuspensionExpires() uint64 {
	if x != nil && x.SuspensionExpires != nil {
		return *x.SuspensionExpires
	}
	return 0
}

func (x *GameAccountInfo) GetSuspensionReason() string {
	if x != nil && x.SuspensionReason != nil {
		return *x.SuspensionReason
	}
	return ""
}

type GameAccountList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameAccounts []*GameAccountInfo `protobuf:"bytes,1,rep,name=game_accounts,json=gameAccounts" json:"game_accounts,omitempty"`
}

func (x *GameAccountList) Reset() {
	*x = GameAccountList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rest_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameAccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameAccountList) ProtoMessage() {}

func (x *GameAccountList) ProtoReflect() protoreflect.Message {
	mi := &file_rest_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameAccountList.ProtoReflect.Descriptor instead.
func (*GameAccountList) Descriptor() ([]byte, []int) {
	return file_rest_login_proto_rawDescGZIP(), []int{8}
}

func (x *GameAccountList) GetGameAccounts() []*GameAccountInfo {
	if x != nil {
		return x.GameAccounts
	}
	return nil
}

var File_rest_login_proto protoreflect.FileDescriptor

var file_rest_login_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x73, 0x74, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x2e, 0x4a, 0x53,
	0x4f, 0x4e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6f, 0x0a, 0x09, 0x46, 0x6f, 0x72,
	0x6d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6d,
	0x61, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x79, 0x0a, 0x0a, 0x46, 0x6f,
	0x72, 0x6d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x6e,
	0x65, 0x74, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x46, 0x6f,
	0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x06, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x73, 0x22, 0x41, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x67, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x3c, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x2e, 0x4a, 0x53, 0x4f,
	0x4e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x22, 0xe4,
	0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x5c,
	0x0a, 0x14, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x6e, 0x65, 0x74, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x13, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x63, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x73, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x22, 0xee, 0x01, 0x0a, 0x0f, 0x47,
	0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x12,
	0x2d, 0x0a, 0x12, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x73, 0x75, 0x73,
	0x70, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x12, 0x2b,
	0x0a, 0x11, 0x73, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x75, 0x73, 0x70, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x5d, 0x0a, 0x0f, 0x47,
	0x61, 0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x4a,
	0x0a, 0x0d, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x6e, 0x65,
	0x74, 0x2e, 0x4a, 0x53, 0x4f, 0x4e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x67, 0x61,
	0x6d, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2a, 0x1a, 0x0a, 0x08, 0x46, 0x6f,
	0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f,
	0x46, 0x4f, 0x52, 0x4d, 0x10, 0x01, 0x2a, 0x48, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x47, 0x41,
	0x4c, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43,
	0x41, 0x54, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x04,
	0x42, 0x27, 0x48, 0x02, 0x5a, 0x23, 0x62, 0x6e, 0x65, 0x74, 0x2d, 0x6d, 0x6f, 0x63, 0x6b, 0x2f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x72,
	0x65, 0x73, 0x74, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
}

var (
	file_rest_login_proto_rawDescOnce sync.Once
	file_rest_login_proto_rawDescData = file_rest_login_proto_rawDesc
)

func file_rest_login_proto_rawDescGZIP() []byte {
	file_rest_login_proto_rawDescOnce.Do(func() {
		file_rest_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_rest_login_proto_rawDescData)
	})
	return file_rest_login_proto_rawDescData
}

var file_rest_login_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rest_login_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rest_login_proto_goTypes = []interface{}{
	(FormType)(0),              // 0: Battlenet.JSON.Login.FormType
	(AuthenticationState)(0),   // 1: Battlenet.JSON.Login.AuthenticationState
	(*ErrorResponse)(nil),      // 2: Battlenet.JSON.Login.ErrorResponse
	(*FormInput)(nil),          // 3: Battlenet.JSON.Login.FormInput
	(*FormInputs)(nil),         // 4: Battlenet.JSON.Login.FormInputs
	(*FormInputValue)(nil),     // 5: Battlenet.JSON.Login.FormInputValue
	(*LoginForm)(nil),          // 6: Battlenet.JSON.Login.LoginForm
	(*LoginResult)(nil),        // 7: Battlenet.JSON.Login.LoginResult
	(*LoginRefreshResult)(nil), // 8: Battlenet.JSON.Login.LoginRefreshResult
	(*GameAccountInfo)(nil),    // 9: Battlenet.JSON.Login.GameAccountInfo
	(*GameAccountList)(nil),    // 10: Battlenet.JSON.Login.GameAccountList
}
var file_rest_login_proto_depIdxs = []int32{
	0, // 0: Battlenet.JSON.Login.FormInputs.type:type_name -> Battlenet.JSON.Login.FormType
	3, // 1: Battlenet.JSON.Login.FormInputs.inputs:type_name -> Battlenet.JSON.Login.FormInput
	5, // 2: Battlenet.JSON.Login.LoginForm.inputs:type_name -> Battlenet.JSON.Login.FormInputValue
	1, // 3: Battlenet.JSON.Login.LoginResult.authentication_state:type_name -> Battlenet.JSON.Login.AuthenticationState
	9, // 4: Battlenet.JSON.Login.GameAccountList.game_accounts:type_name -> Battlenet.JSON.Login.GameAccountInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rest_login_proto_init() }
func file_rest_login_proto_init() {
	if File_rest_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rest_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormInputs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormInputValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginForm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRefreshResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameAccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rest_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameAccountList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rest_login_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rest_login_proto_goTypes,
		DependencyIndexes: file_rest_login_proto_depIdxs,
		EnumInfos:         file_rest_login_proto_enumTypes,
		MessageInfos:      file_rest_login_proto_msgTypes,
	}.Build()
	File_rest_login_proto = out.File
	file_rest_login_proto_rawDesc = nil
	file_rest_login_proto_goTypes = nil
	file_rest_login_proto_depIdxs = nil
}
